global using BuildingBlocks.CQRS;
global using Carter;
global using Catalog.API.Configurations;
global using Catalog.API.Exceptions;
global using Catalog.API.Models;
global using FluentValidation;
global using JasperFx;
global using Mapster;
global using Marten;